name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: infdesc.tex
          compiler: pdflatex
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: infdesc.pdf
      
